queue_rules:
  - name: default
    conditions:
      - base=main
      - label=ci:ready_to_merge
   
pull_request_rules:
  - name: push to default merge queue
    conditions:
      - base=main
      - label=ci:ready_to_merge
    actions:
      queue:
        name: default
        require_branch_protection: true
        method: squash

  - name: error reporting
    conditions:
      - check-success=trivial
    actions:
      comment:
        message: >
          @{{author}}: Failure in {{check_success}}. Click the details link
          beside the appropriate entry in the check suite list below.
      label:
        add:
          - ci:issue
        remove:
          - ci:ready_to_merge
          
  - name: remove mergify label
    conditions:
      - merged
    actions:
      label:
        remove:
          - ci:ready_to_merge 

