queue_rules:
  - name: default
    conditions:
      - base=main
      - label=ci:trigger
   
pull_request_rules:
  - name: push to default merge queue
    conditions:
      - base=main
    actions:
      queue:
        name: default
        require_branch_protection: true
        method: squash

  - name: remove mergify label
    conditions:
      - merged
    actions:
      label:
        remove:
          - ci:trigger

