on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main
  pull_request_review: {}
      

jobs:
  trivial:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:action_test')
      
    name: show github.event
    steps:
      - name: check object
        run: |
          cat << OBJECT
          ${{ toJson(github.event) }}
          OBJECT
