on:
  pull_request:
    types: [synchronize, labeled]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:action_test')
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ci:flag']
            })
