name: Manage Labels
on:
  pull_request_target:
    types:
      - synchronize
      - labeled

jobs:
  apply_cirun:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'ci:ready_to_merge'))
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.BOT_TOKEN }} 
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ci:run']
            })

  label_cleanup:
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled'
    name: remove CI runner labels
    steps:
      - name: remove tags
        uses: actions/github-script@a3e7071a34d7e1f219a8a4de9a5e0a34d1ee1293
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          script: |
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'ci:run'
            })
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'ci:test'
            })
        # Prevent erroring out if label doesn't exist
        continue-on-error: true

