name: PR approved 

on:
  pull_request_review:
    types: [submitted]

jobs:
  dump-object:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo ${{ github.event.review.state }}
