name: Send PR
on:
  pull_request_review:
    types: [submitted]

jobs:
  send_pr:
    runs-on: ubuntu-latest
    name: archive pr number
    if: github.event.review.state == 'approved'

    steps:
      - name: save pr number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
