on:
  workflow_dispatch: {}

jobs:
  failit:
    runs-on: ubuntu-latest
    steps:
    - run: |
        return 1
    - name: error trapping
      if: ${{ failure() }}
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"